### ISSUE TITLE
Can i ask the TMS service feature on the gscloud roadmap?

### ISSUE THREAD

**Issue by paranlee** [geoserver/geoserver-cloud#103]
I check the container hub. and I found wps, wcs, wms, wfs supported on msa services.
https://hub.docker.com/u/geoservercloud

On the official gscloud [homepage](http://geoserver.org/geoserver-cloud/), 
[docker-compose.yml service](https://geoserver.github.io/geoserver-cloud/deploy/docker-compose/stable/docker-compose.yml) have shown WFS, WMS services.

![image](https://user-images.githubusercontent.com/43713967/135205081-0403f17d-f743-4937-95f8-7d3c91afce68.png)

Can i ask TMS service support will be on the gscloud roadmap?
If necessary, can I make a patch that TMS support ?

In origin geoserver support below services.
![image](https://user-images.githubusercontent.com/43713967/135205330-1574985e-8e70-4f46-92df-dfe4535acfa5.png)

**Comment by groldan** [comment]
You got it, [1.0-RC10](https://github.com/geoserver/geoserver-cloud/releases/tag/v1.0-RC10) comes with a fully functional gwc-service. Try the latest [docker-compose.yml](https://raw.githubusercontent.com/geoserver/geoserver-cloud/main/docs/deploy/docker-compose/stable/shared_datadir/docker-compose.yml)
