### ISSUE TITLE
Manual for running GeoServer Cloud with podman and RHEL/CentOS

### ISSUE THREAD

**Issue by allanin** [geoserver/geoserver-cloud#110]
Hi there,

besides docker there is podman, which is a OCI-compliant container runtime: [podman](https://podman.io/)

It should also be able to run GeoServer Cloud in combination with Red Hat 8.x or Centos 8 (Stream).

Please provide a manual for running GeoServer with podman.

Thanks

**Comment by groldan** [comment]
Closing as fixed by #111 and 78cdd8367c7008640b87089c688139daaae982e3
