### ISSUE TITLE
GeoServer Vanilla / GeoServer Cloud configuration compatibility

### ISSUE THREAD

**Issue by AlexGacon** [geoserver/geoserver-cloud#122]
Hi,

Can the configuration data_dir of a vanilla GeoServer be used with a GeoServer Cloud deployment?

My idea is to allow some GIS administrator to use a vanilla GeoServer web UI with additionnal extensions for styling (css, mapbox, geostyler) and then use the configuration of this instance to do the deployment of a GeoServer Cloud cluster.

Regards
Alexandre

**Comment by AdrienVH** [comment]
Hi Alex !
I don't know if you know it, but GeoServer Cloud comes with the usual administration WebUI.
If you NEED to have two different envs (a vanilla-one for dev purposes and a cloud-one for production), I'm wondering if there is a solution to use a Github repository to store your xml file based configuration... I can't remember if this option allows you to store it as a vanilla data_dir or as a more modern way (yaml style)... In this case, it would be irrelevant to you.

**Comment by AlexGacon** [comment]
Hello Adrien !
I saw that the usual administration WebUI is available in GeoServer Cloud but since I would like to have additional extensions in it, I wonder if it is something possible with the WebUI. I had a glance on the WebUI source : there is an option for the importer plugin but no other plugin are available.

If it is possible to add extensions to the UI, the cloud one is good enough for me!

**Comment by groldan** [comment]
Closing as stale
