### ISSUE TITLE
Unable to clone repo

### ISSUE THREAD

**Issue by securedimensions** [geoserver/geoserver-cloud#123]
Tried to build geoserver-cloud on CENTOS 7 (`Linux version 3.10.0-1127.19.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Tue Aug 25 17:23:54 UTC 2020`) following the documentation at http://geoserver.org/geoserver-cloud/develop/#building

The command `git clone --recursive https://github.com/geoserver/geoserver-cloud.git`fails:

````
Cloning into 'geoserver-cloud'...
remote: Enumerating objects: 11782, done.
remote: Counting objects: 100% (2342/2342), done.
remote: Compressing objects: 100% (1319/1319), done.
remote: Total 11782 (delta 960), reused 1833 (delta 593), pack-reused 9440
Receiving objects: 100% (11782/11782), 5.85 MiB | 0 bytes/s, done.
Resolving deltas: 100% (4877/4877), done.
Submodule 'config' (git@github.com:geoserver/geoserver-cloud-config.git) registered for path 'config'
Cloning into 'config'...
Warning: Permanently added the ECDSA host key for IP address '140.82.121.4' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:geoserver/geoserver-cloud-config.git' into submodule path 'config' failed
````

**Comment by groldan** [comment]
Hey, sorry for the inconvenience. Problem was the config submodule was using git (ssh) protocol instead of https so it required authenticated access.

It should work now, I've changed it to https://github.com/geoserver/geoserver-cloud-config

**Comment by securedimensions** [comment]
Cheers!
