### ISSUE TITLE
COG (Cloud Optimized GeoTIFF) Support

### ISSUE THREAD

**Issue by groldan** [geoserver/geoserver-cloud#131]

**Comment by Xientist** [comment]
Hello,

We are running a cloud architecture and need to serve geodata for one of our components.
I have been trying to add the dependency to the COG community plugin and to recompile the project.

Compilation worked without issues, however the web UI does not seem to be updated as expected.
The plugin does not seem to replace the original geotiffRaster panel in the datastore creation page.

If needed, I can give more specific info on the steps I took to try this.
Could you give me advice on how I could make it work?
