### ISSUE TITLE
CQL Filtering not working on WMS

### ISSUE THREAD

**Issue by woutergd** [geoserver/geoserver-cloud#181]
This project is very nice, great to see how this improves handling Geoserver in large environments. I am testing it in a small environment, but found out that the CQL filtering is not working on WMS. Is this a known issue? I already checked the code how the WMS is generated, but can't find any specific remarks that can cause this issue as it redirects the requests almost complete into the dispatcher.

If anyone can help me to point me in the right direction I am happy to work on a fix myself, or if this can be fixed it would be great either.

**Comment by groldan** [comment]
Hi, thanks.

It's not a known issue, I'll take a look later today. My feeling is the autoconfiguration is missing to load some specific  bean. Did you see a stack trace in the wms service logs when doing a request with cql filters?

**Comment by woutergd** [comment]
Hi @groldan,

I hadn't seen any specific stack trace or error when using cql, as far as I could see at the moment it looks like the query parameter was just ignored. I will dig a bit deeper this evening to see if there is somewhere else maybe a specific stack trace or maybe warning message.

**Comment by woutergd** [comment]
Thanks for checking and you response, I see what you mean in the code. What is the preferred solution for this, maybe I can provide help by making a fix for this issue. I assume the expected solution is not just adding the gs-wfs to the WMS microservice, but a more specific way that just adds the missing parser?

**Comment by groldan** [comment]
Just created a pull request, you can see the fix [here](https://github.com/geoserver/geoserver-cloud/pull/182/files#diff-83197316d1cf09d4a8b96eb6cc08a2e00d4959ab8360c43905f70a4da59aeeabR27), it's to let our custom `FilteringXmlBeanDefinitionReader` know it has to load those beans from `gs-wfs.jar!/applicationContext.xml`

**Comment by groldan** [comment]
> I assume the expected solution is not just adding the gs-wfs to the WMS microservice

Not just that, no. Unfortunately the gs-wms, gs-wfs, gs-wcs, gs-gwc jars need to be present in all services classpaths,
just because they contain the different `ServiceInfo` concrete subtypes (i.e. `WMSInfo`, `WFSInfo`, `WCSInfo`, `WMTSInfo`).
Otherwise, for example, the `wms-service` catalog would fail to load due to missing configuration classes.
So what we do is to exclude the transitive dependencies (e.g. `wfs-service` needs `gs-wms` on the classpath, but not all
the other dependencies `gs-wms` would carry over as transitive).

**Comment by groldan** [comment]
in any case thanks for offering to contribute, keep that spirit, I'll be more than glad to guide you, I just saw your comment too late.

**Comment by woutergd** [comment]
Thats a quick fix! Interesting to see how this is structured, I am a bit new to developing for geoserver but tried in the past several internal modifications. Working with this solution is of course structured a bit different, converting something into microservices is of course not the easiest thing to do when moving away from a monolith. 

Are there also plans to restructure in the end the Geoserver source to move all those shared objects into a shared jar that is used by all the other parts of the application, to get rid in the end of these cross-app references? Or is that a development that is too large to get done?

I will check the new docker images soon when these are compiled and published to see if everything is resolved, and will test this solution further and let you know if I find anything else.

**Comment by groldan** [comment]
> Are there also plans to restructure in the end the Geoserver source to move all those shared objects into a shared jar that is used by all the other parts of the application, to get rid in the end of these cross-app references? Or is that a development that is too large to get done?

I don´t think so because in upstream geoserver, the `ServiceInfo` implementations are supposed to be dynamically loaded. Like in if you create a new `FooService` and drop the jars in WEB-INF/lib, and it implements the correct extension point, then it'll automatically support that new kind of service. Guess it'd break if you remove the jars though, or try to import the datadir on an instance that doesn't have them.

**Comment by groldan** [comment]
PR succeeded and merged, you'll need to wait for [this CI job](https://github.com/geoserver/geoserver-cloud/runs/5161456027?check_suite_focus=true) to finish to test the new docker images (1.0-SNAPSHOT, or wait until the next RC).

Cheers.

**Comment by woutergd** [comment]
Just to let you know, just updated the WMS microservice with the latest build, everything around filtering works fine now!
