### ISSUE TITLE
How to inject ImagePyramid plugin into GeoServer cloud

### ISSUE THREAD

**Issue by andermirik** [geoserver/geoserver-cloud#209]
Hi, Could you tell us how to inject plugin [ImagePyramid](https://docs.geoserver.org/stable/en/user/data/raster/imagepyramid.html#imagepyramid-install) plugin into geoserver cloud.

**Comment by groldan** [comment]
Hi @andermirik ,  shouldn't be hard at all, just created #224 to track it down.

If you're up to give it a shot, a pull request would be welcome.
It's probably just a matter of adding the dependency to the `gs-cloud-starter-raster-formats` pom and testing it works.

**Comment by groldan** [comment]
Closing, implemented at #379, available since v1.5.0
