### ISSUE TITLE
topp:states layer is not displayed correctly

### ISSUE THREAD

**Issue by ianturton** [geoserver/geoserver-cloud#231]
With a vanilla docker setup and a default GeoServer data directory the WMS1.1.0 topp:states layer displays twisted - this is in both Layer Preview and QGis. If you turn on ignore axis order in QGis or switch to 1.3.0 in Layer preview then the map is still rotated but is now in Antarctica. 

![topp-statesx](https://user-images.githubusercontent.com/122529/169850467-d43be28b-01fd-4172-9b14-dc8f1cfac18d.png)

**Comment by groldan** [comment]
Hi Ian, see the comment in #234, that should fix it. Thanks for reporting.
Please tell me if you have a chance to verify it on 1.0-SNAPSHOT.
