### ISSUE TITLE
Configure data_directory to point to Azure Blob Container

### ISSUE THREAD

**Issue by bruschke** [geoserver/geoserver-cloud#258]
Getting started with geoserver-cloud.  Trying to add a Shapefile type store.  Is there a way to update the Shapefile location Data Directory to point to an Azure Blob Container?

![image](https://user-images.githubusercontent.com/72035394/176969594-30236ccc-aca3-426f-b478-65456337dae7.png)

We are using the docker-compose with JDBCConfig.

**Comment by groldan** [comment]
you mount the blob store as a volume on all geoserver containers (webui,wfs,wms,wcs,rest,gwc) using the same mount point (e.g. /mnt/azure or whatever) and configure it normally in the webui.

If you want the webui to show the filesystem contents, set the [geoserver.web-ui.file-browser.hide-file-system](https://github.com/geoserver/geoserver-cloud-config/blob/master/geoserver.yml#L179) config property to `false`

https://azure.microsoft.com/en-us/blog/persistent-docker-volumes-with-azure-file-storage/
