### ISSUE TITLE
Unable to create a layer from a pregeneralized datastore

### ISSUE THREAD

**Issue by AlexGacon** [geoserver/geoserver-cloud#279]
When I try to create a layer from a pregeneralized datastore, the creation fails with errors.

**REST API**
If I use the REST API, I got the following error in logs 
`java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "f" is null
	at org.geoserver.data.gen.DSFinderRepository.getURLForLocation(DSFinderRepository.java:46) ~[gs-feature-pregeneralized-2.21.0-CLOUD.jar:2.21.0-CLOUD]`

If I try to create a new layer from the datastore in the admin UI, the layer is marked as "Published" but it is not visible in the Layers page. But if I send a GET request for the layer, I managed to have a definition of the layer.

**ADMIN UI**
If I try to do the creation from the admin UI, I got exactly the same error message but the REST API doesn't list the layer as in the first case

**Comment by AlexGacon** [comment]
The behavior for the REST API is confirmed with a GS Cloud instance using a data_dir instead of the JDBC stores.

**Comment by groldan** [comment]
@AlexGacon where can I get a sample pregeneralized store's data and definition to replicate?

**Comment by groldan** [comment]
> The behaviors for the REST API and the admin UI are confirmed with a GS Cloud instance using a data_dir instead of the JDBC stores.

what do you mean confirmed? that it works with the datadir catalog backend but fails with the jdbcconfig one?

**Comment by AlexGacon** [comment]
Tested on GeoServer Vanilla with JDBC config and resource store : I managed to create the layer but the overview of it is not working.
![image](https://user-images.githubusercontent.com/3034717/205587285-fde6df0c-d2b2-4eed-830a-c1f5313e8734.png)

I will create an issue in GeoServer (and probably GeoTools) JIRA.
