### ISSUE TITLE
GWC Rest API - GET specific layer does not work

### ISSUE THREAD

**Issue by AlexGacon** [geoserver/geoserver-cloud#311]
Tested on RC30

GET {{geoserver_url}}/gwc/rest/layers works and shows all the expected layers

GET {{geoserver_url}}/gwc/rest/layers/ne:world does not work -> GS cloud states that the layer is unknown

The endpoint works fine on vanilla GS.

**Comment by AlexGacon** [comment]
Link to #313. Only the GWC layers created with the admin UI are not available in the detail endpoint. A GWC layer created through the REST API is available.

**Comment by mzaveiro** [comment]
I can confirm it also happens to me on RC30. 

I had to downgrade to RC28.

**Comment by groldan** [comment]
So far what we've found is the error is produced when the GWC rest api tries to encode a GeoServerTileLayer using XStream.
Problem is the XStream encoder it uses defaults to using reflection, and that doesn't work with Java 17. It does work with Java 11, but Java 17 is stricter about the use of reflection.
