### ISSUE TITLE
Is WPS Capability still exposed/functioning even if the service is not used?

### ISSUE THREAD

**Issue by haithamshahin333** [geoserver/geoserver-cloud#329]
Hello! New to GeoServer - the docs note that the WPS Service is not implemented. Does this mean certain capabilities of GeoServer are not functional in this architecture?

**Comment by groldan** [comment]
Hi, the WPS service is currently not working. On the bright side @jemacchi is working to re-enable it. Keep tuned.

**Comment by jemacchi** [comment]
hi ! hope soon to provide some news on this topic.

**Comment by groldan** [comment]
WPS is available now in [1.2.0](https://github.com/geoserver/geoserver-cloud/releases/tag/v1.2.0)
