### ISSUE TITLE
CORS is not working when using headers in request

### ISSUE THREAD

**Issue by AlexGacon** [geoserver/geoserver-cloud#344]
When you try to use WFS request on a GS Cloud environment with headers, the request is rejected because of CORS.

It is solved by adding allowedHeaders: "*" into gateway-service.yml.

It should be part of the default configuration IMO.

**Comment by groldan** [comment]
Fixed at https://github.com/geoserver/geoserver-cloud-config/commit/53034be5c53fb0364377bff67b29b4cc58bb9afa
