### ISSUE TITLE
Pyramid plugin extension for coverage store in geoserver-cloud

### ISSUE THREAD

**Issue by shomy4** [geoserver/geoserver-cloud#359]
Hi, i would like the possibility to use pyramid plugin extension in geoserver cloud.
Could you give me the directions on how to implement it?
Is there some plugin which you incorporated in geoserver-cloud for which steps are similar, so i can use it as a blueprint.

**Comment by shomy4** [comment]
Im trying to add pyramid plugin into geoserver-cloud project and installed all project dependencies as specified in the README:
```
openjdk 19.0.2 2023-01-17
javac 19.0.2
Apache Maven 3.6.3
Docker version 24.0.5
docker-compose version 1.29.2
```
yet when i run:
`
make install
`
I get the following build error:
`[ERROR] Failed to execute goal on project gs-cloud-starter-vector-formats: Could not resolve dependencies for project org.geoserver.cloud:gs-cloud-starter-vector-formats:jar:1.5-SNAPSHOT: Could not find artifact org.geoserver.extension:gs-feature-pregeneralized:jar:2.24.0-CLOUD in osgeo-releases (https://repo.osgeo.org/repository/release/) -> [Help 1]
[ERROR] Failed to execute goal on project gs-cloud-catalog-plugin: Could not resolve dependencies for project org.geoserver.cloud.catalog:gs-cloud-catalog-plugin:jar:1.5-SNAPSHOT: The following artifacts could not be resolved: org.geoserver:gs-main:jar:2.24.0-CLOUD, org.geoserver:gs-main:jar:tests:2.24.0-CLOUD, org.geoserver:gs-wms:jar:2.24.0-CLOUD, org.geoserver:gs-wfs:jar:2.24.0-CLOUD, org.geoserver:gs-wcs:jar:2.24.0-CLOUD, org.geoserver:gs-gwc:jar:2.24.0-CLOUD, org.geoserver.extension:gs-wps-core:jar:2.24.0-CLOUD: Could not find artifact org.geoserver:gs-main:jar:2.24.0-CLOUD in osgeo-releases (https://repo.osgeo.org/repository/release/) -> [Help 1]
[ERROR] Failed to execute goal on project gs-cloud-starter-raster-formats: Could not resolve dependencies for project org.geoserver.cloud:gs-cloud-starter-raster-formats:jar:1.5-SNAPSHOT: The following artifacts could not be resolved: org.geoserver.community:gs-pgraster:jar:2.24.0-CLOUD, org.geoserver.community:gs-cog:jar:2.24.0-CLOUD, org.geoserver.web:gs-web-core:jar:2.24.0-CLOUD: Could not find artifact org.geoserver.community:gs-pgraster:jar:2.24.0-CLOUD in osgeo-releases (https://repo.osgeo.org/repository/release/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :gs-cloud-starter-vector-formats
make: *** [Makefile:16: install] Error 1
`
Is there an issue with geoserver-cloud related mvn repository?

**Comment by groldan** [comment]
Did you run `make` or `make deps` before `make install`?
