### ISSUE TITLE
WMTS issue on podman deployment

### ISSUE THREAD

**Issue by ppradela** [geoserver/geoserver-cloud#399]
In the podman-style deployment documentation there is no information about creating a container based on gwc image. Without a gwc container WMTS service will not work.

**Comment by groldan** [comment]
I see. I guess when we created the podman deployment examples gwc wasn't yet integrated.
Since then we're not actively using podman anymore, but it's certainly something I'd like to have tested.
How do you feel about making your first pull request?

**Comment by ppradela** [comment]
@groldan 
What do you mean by saying/writing "How do you feel about making your first pull request?"

**Comment by groldan** [comment]
hi, I mean you making a contribution to the podman-style deployment documentation

**Comment by ppradela** [comment]
I can do it. ;)

**Comment by ppradela** [comment]
Hi @groldan! I have made a pull request

**Comment by groldan** [comment]
Fixed by #430
