### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by ppradela** [geoserver/geoserver-cloud#429]
Is it possible to add an SSL certificate to webui?
I was trying to host it behind nginx-proxy-manager but I am getting a warning when I am sending credentials and I am also getting bad requests (400) when I want to list enabled modules from the server info page.
If someone has a guide how to add a certificate to webgui, please share it ;)

**Comment by ppradela** [comment]
I found a workaround for my case. I put nginx-proxy-manager in the same network and in order to go on the Geoserver settings etc. it just forwards requests directly to webui container.

**Comment by groldan** [comment]
You can follow this guide: https://spring.io/blog/2023/06/07/securing-spring-boot-applications-with-ssl

For example, mount a `ssl.yml` file in the pod at `/etc/geoserver/ssl.yml`, and run the webui service with `JAVA_OPTS=-Dspring.config.additional-location=/etc/geoserver/ssl.yml`
