### ISSUE TITLE
how to enabled  Authkey Extension

### ISSUE THREAD

**Issue by giserzhangwl** [geoserver/geoserver-cloud#442]
how to enabled  Authkey Extension。

GeoServer-Cloud version 1.7.0

<img width="1113" alt="image" src="https://github.com/geoserver/geoserver-cloud/assets/36870442/2fd9b952-4c2f-4d3f-8cd4-91bf6627a534">

**Comment by groldan** [comment]
just set the env variable `GEOSERVER_SECURITY_AUTHKEY` to `true`.
It's enabled by default in 1.8.0 though
See here: https://github.com/geoserver/geoserver-cloud-config/blob/v1.8.0/geoserver.yml#L55
