### ISSUE TITLE
Replication Issues with WEBUI Container on Kubernetes

### ISSUE THREAD

**Issue by TomIraz** [geoserver/geoserver-cloud#448]
Hello team,

I wanted to report a problem I'm experiencing when trying to replicate the WEBUI service in a Kubernetes environment.

Problem:
When trying to create more than one replica of the pod in Kubernetes, I have noticed that the authentication system fails. Despite entering the correct username and password, the system repeatedly redirects me to the login page as if I had never logged in.

**Comment by groldan** [comment]
Hi, the webui is not supposed to be scaled out. It is the only one that can't, because it depends on the servlet session.
Hence, if you scale it out, the gateway will load balance to all available webui pods, but only one of them will have the session open.

I'm closing the issue.
