### ISSUE TITLE
HTTPS support in gateway

### ISSUE THREAD

**Issue by ppradela** [geoserver/geoserver-cloud#464]
Is it possible to configure ssl in gateway service? How to add additional config (https://spring.io/blog/2023/06/07/securing-spring-boot-applications-with-ssl)? I have tried to bind ssl.yml:/etc/geoserver/ssl.yml and added JAVA_OPTS: "-Dspring.config.additional-location=/etc/geoserver/ssl.yml" in docker-compose.yaml but gateway container doesn't load it. I bind ./server.p12:/etc/geoserver/server.p12 and change classpath:server.p12 to file:/etc/geoserver/server.p12 in ssl.yml config. I am not familiar with Spring. Can anybody help me?

**Comment by sameersheikh22** [comment]
@ppradela 
I'm currently facing the same issue. Did you manage to get any help or find a solution?

**Comment by ppradela** [comment]
@sameersheikh22 
I am using a caddy as a reverse proxy for now. A caddy container has to be in the same container network. My Caddyfile looks like:

gscloud.example.com {
    tls cert.pem key.pem
    reverse_proxy webui:8080
    reverse_proxy /ows* gateway:8080
    reverse_proxy /gwc* gateway:8080
}

**Comment by Ravi-170524** [comment]
@ppradela 
we are getting below error for this caddyfile
caddyfile::
geoserver-cloud.vassarlabs.com {
  redir https://{host}{uri}
  tls /etc/letsencrypt/live/geoserver-cloud.vassarlabs.com/fullchain.pem /etc/letsencrypt/live/geoserver-cloud.vassarlabs.com/privkey.pem
  reverse_proxy localhost:9090 {
    header_up X-Forwarded-Host {host}
  }
}
Error:
![Screenshot from 2024-06-04 19-41-33](https://github.com/geoserver/geoserver-cloud/assets/136073671/2ab0fe95-100a-4d7c-9516-930b08ce2da3)
Can anyone help me!

**Comment by ppradela** [comment]
@Ravi-170524 
Compare my Caddyfile and your. You have to do reverse_proxy directly to webui for the geoserver admin interface and another route for services.

**Comment by Ravi-170524** [comment]
@ppradela 
Thanks , It is working fine
