### ISSUE TITLE
pgconfig counld not deploy

### ISSUE THREAD

**Issue by tpolong** [geoserver/geoserver-cloud#500]
![b92e4f38bd0a19a65e76cd9aa062ec3](https://github.com/user-attachments/assets/7abb6ef7-8641-40f1-8346-c5c0758c2b9f)
![f21cf134aff755a38b00afbf0a90d1b](https://github.com/user-attachments/assets/d292ea58-1c2f-4ae3-9b91-3ec5e8c2013f)
![cf082c8e1e996853833c25c67b720cd](https://github.com/user-attachments/assets/dc9d2a16-c35a-493e-b52a-8ad94fe46eb8)

**Comment by groldan** [comment]
once the webui service is ready, it can take some seconds for the gateway to notice it.
how long did you wait? have you retried several times until the gateway can connect to webui?
or do you have any more information?

**Comment by tpolong** [comment]
You were right. After waiting for a while, the page appeared.
