### ISSUE TITLE
wms publish error

### ISSUE THREAD

**Issue by tpolong** [geoserver/geoserver-cloud#509]
org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.integration.amqp.outbound.AmqpOutboundEndpoint@40edba7d]; nested exception is org.springframework.amqp.AmqpIOException: java.net.UnknownHostException: rabbitmq, failedMessage=GenericMessage [payload=byte[1516], headers={id=301a109c-a7a1-b1d6-dc7c-7562f8ba367b, contentType=application/json, target-protocol=amqp, timestamp=1725853483207}]
![image](https://github.com/user-attachments/assets/f8e9d354-b15b-46d9-8655-028f63fb7fae)

**Comment by groldan** [comment]
`java.net.UnknownHostException: rabbitmq`: looks like your rabbitmq container died?

I can reproduce by going to the layer edit page, then do `docker compose kill rabbitmq`, back to the layer edit page, click save, and get that same error.

Once I do `docker compose up -d rabbitmq` I can save the layer.

Now, why your rabbitmq container is down I can't tell.

**Comment by tpolong** [comment]
![image](https://github.com/user-attachments/assets/51855c84-0d56-40d9-8da0-4ebcec0d7d7a)

**Comment by tpolong** [comment]
I use geoservercloud 1.8.11  and publish sucess
