### ISSUE TITLE
helm chart: set up basic auto scaling

### ISSUE THREAD

**Issue by groldan** [geoserver/geoserver-cloud#522]

**Comment by jemacchi** [comment]
After some talks, we decided: 
- to use k8s native hpa, and to create a related template in context of [helm-application ](https://github.com/camptocamp/helm-application/)
- apply it in helm-geoserver-cloud
- continue R&D with [Keda](https://keda.sh/) for next stages on autoscaling (including events based scaling)

**Comment by jemacchi** [comment]
Once this [PR](https://github.com/camptocamp/helm-application/pull/240) is approved, then we can test the autoscaling in context of helm-geoserver-cloud (just importing a new release of the helm-application chart dependency)

**Comment by groldan** [comment]
* Introduced as a new feature upstream: https://github.com/camptocamp/helm-application/pull/239
* Released as [helm-application:2.9.0](https://github.com/camptocamp/helm-application/releases/tag/2.9.0)

**Comment by groldan** [comment]
* HPA Auto-Scaling example pull request for the helm chart is here: https://github.com/camptocamp/helm-geoserver-cloud/pull/254
* Once this is merged and a new chart version is released we can close this issue

**Comment by groldan** [comment]
Released helm chart `2.3.0` with gscloud `1.8.12` and HPA integration https://github.com/camptocamp/helm-geoserver-cloud/pull/254
