### ISSUE TITLE
Support for DXF and Geopackage extension

### ISSUE THREAD

**Issue by woutergd** [geoserver/geoserver-cloud#531]
We are verifying if it is possible to integrate the dxf and geopackage output format extensions within Geoserver Cloud. Is there any specific reason that these are currently excluded, or is just due to different priorities that they haven't been added?

Links to the extensions:
- https://docs.geoserver.org/stable/en/user/extensions/dxf/index.html
- https://docs.geoserver.org/stable/en/user/extensions/geopkg-output/index.html

**Comment by buehner** [comment]
Hi. I don't think that there are technical/blocking reasons that the dxf extension is not (yet) available. For GeoServer Cloud, we always need special code/config to make extensions available. So I guess someone "just has to do it" (at least in case of "simple" extensions" it shouldn't be that hard).

I always wanted to try to make a new extension available for geoserver cloud, so maybe I will find some time within the next days to give the DXF one a try. I will let you know here

**Comment by woutergd** [comment]
@buehner  thanks for your response, good to hear that there are no practical limitations on this addition. 

I was already working on the integration, so see the PR over here: https://github.com/geoserver/geoserver-cloud/pull/542 with probably the required modifications. If there is anything that need to be changed, just let me know.

**Comment by mehul-bayer** [comment]
Is there any documentation outlining the steps or a procedure to add extensions?

**Comment by groldan** [comment]
Closing as fixed by #543
