### ISSUE TITLE
Edit Workspce Service  invalid

### ISSUE THREAD

**Issue by SkyvenXiong** [geoserver/geoserver-cloud#560]
![image](https://github.com/user-attachments/assets/8b187a3e-cc4b-415b-9176-1d8cc3b98743)

then  open  this workspace agen , it have no effect

![image](https://github.com/user-attachments/assets/96b26186-2bd3-4d2d-87a3-76fa504a6d22)

**Comment by groldan** [comment]
@SkyvenXiong thanks for reporting. Indeed it is a bug with the `pgconfig` catalog backend when `geoserver.catalog.caching.enabled=true`, which is the default config.

[This pull request](#565) should fix it for good. Once it's merged, can you give `1.9-SNAPSHOT` a shot?

**Comment by groldan** [comment]
FYI the bug is fixed for good, it required both #565 and #567

**Comment by SkyvenXiong** [comment]
@groldan    nice to hear this news ,I will have a try soon, thinks
